-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:b7f287e2d0bedf46080df3aec41ae200$
-- 

return {
	texture = 'sheet_char.png',
	frames = {
			{
				name = "Clem_idle1",
				spriteColorRect = { x = 17, y = 4, width = 32, height = 73 },
				uvRect = { u0 = 0.300781, v0 = 0.355469, u1 = 0.585938, v1 = 0.417969 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Clem_idle2",
				spriteColorRect = { x = 17, y = 4, width = 32, height = 73 },
				uvRect = { u0 = 0.601562, v0 = 0.347656, u1 = 0.886719, v1 = 0.410156 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Clem_walk1",
				spriteColorRect = { x = 15, y = 4, width = 34, height = 73 },
				uvRect = { u0 = 0.0078125, v0 = 0.328125, u1 = 0.292969, v1 = 0.394531 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Clem_walk2",
				spriteColorRect = { x = 17, y = 2, width = 32, height = 75 },
				uvRect = { u0 = 0.0078125, v0 = 0.261719, u1 = 0.300781, v1 = 0.324219 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Clem_walk3",
				spriteColorRect = { x = 17, y = 4, width = 32, height = 73 },
				uvRect = { u0 = 0.601562, v0 = 0.28125, u1 = 0.886719, v1 = 0.34375 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Nils_idle1",
				spriteColorRect = { x = 13, y = 2, width = 36, height = 75 },
				uvRect = { u0 = 0.328125, v0 = 0.207031, u1 = 0.621094, v1 = 0.277344 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Nils_idle2",
				spriteColorRect = { x = 13, y = 4, width = 36, height = 73 },
				uvRect = { u0 = 0.308594, v0 = 0.28125, u1 = 0.59375, v1 = 0.351562 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Nils_walk1",
				spriteColorRect = { x = 13, y = 2, width = 36, height = 75 },
				uvRect = { u0 = 0.628906, v0 = 0.132812, u1 = 0.921875, v1 = 0.203125 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Nils_walk2",
				spriteColorRect = { x = 13, y = 4, width = 36, height = 73 },
				uvRect = { u0 = 0.628906, v0 = 0.207031, u1 = 0.914062, v1 = 0.277344 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Nils_walk3",
				spriteColorRect = { x = 13, y = 2, width = 36, height = 75 },
				uvRect = { u0 = 0.328125, v0 = 0.132812, u1 = 0.621094, v1 = 0.203125 },
				spriteSourceSize = { width = 64, height = 77 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_idle1",
				spriteColorRect = { x = 0, y = 8, width = 80, height = 64 },
				uvRect = { u0 = 0.0078125, v0 = 0.132812, u1 = 0.320312, v1 = 0.257812 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_idle2",
				spriteColorRect = { x = 0, y = 8, width = 80, height = 64 },
				uvRect = { u0 = 0.648438, v0 = 0.00390625, u1 = 0.960938, v1 = 0.128906 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_walk1",
				spriteColorRect = { x = 0, y = 8, width = 80, height = 64 },
				uvRect = { u0 = 0.328125, v0 = 0.00390625, u1 = 0.640625, v1 = 0.128906 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_walk2",
				spriteColorRect = { x = 0, y = 8, width = 80, height = 64 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.320312, v1 = 0.128906 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "kitty_idle1",
				spriteColorRect = { x = 8, y = 2, width = 44, height = 64 },
				uvRect = { u0 = 0.539062, v0 = 0.503906, u1 = 0.789062, v1 = 0.589844 },
				spriteSourceSize = { width = 64, height = 66 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "kitty_idle2",
				spriteColorRect = { x = 8, y = 0, width = 44, height = 66 },
				uvRect = { u0 = 0.273438, v0 = 0.421875, u1 = 0.53125, v1 = 0.507812 },
				spriteSourceSize = { width = 64, height = 66 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "kitty_walk1",
				spriteColorRect = { x = 8, y = 0, width = 44, height = 66 },
				uvRect = { u0 = 0.59375, v0 = 0.414062, u1 = 0.851562, v1 = 0.5 },
				spriteSourceSize = { width = 64, height = 66 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "kitty_walk2",
				spriteColorRect = { x = 8, y = 2, width = 44, height = 64 },
				uvRect = { u0 = 0.0078125, v0 = 0.488281, u1 = 0.257812, v1 = 0.574219 },
				spriteSourceSize = { width = 64, height = 66 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "kitty_walk3",
				spriteColorRect = { x = 8, y = 0, width = 44, height = 66 },
				uvRect = { u0 = 0.0078125, v0 = 0.398438, u1 = 0.265625, v1 = 0.484375 },
				spriteSourceSize = { width = 64, height = 66 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

