-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:d133e3e83ebb9ec68823902f5742bce3$
-- 

return {
	texture = 'sheet_map.png',
	frames = {
			{
				name = "bg/grass_1",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.738281, v0 = 0.445312, u1 = 0.894531, v1 = 0.523438 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bg/grass_2",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.738281, v0 = 0.365234, u1 = 0.894531, v1 = 0.443359 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj/cabin",
				spriteColorRect = { x = 9, y = 5, width = 150, height = 142 },
				uvRect = { u0 = 0.441406, v0 = 0.335938, u1 = 0.734375, v1 = 0.474609 },
				spriteSourceSize = { width = 160, height = 160 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/cabin_con",
				spriteColorRect = { x = 17, y = 85, width = 142, height = 62 },
				uvRect = { u0 = 0.300781, v0 = 0.367188, u1 = 0.421875, v1 = 0.505859 },
				spriteSourceSize = { width = 160, height = 160 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "obj/lodge",
				spriteColorRect = { x = 0, y = 7, width = 240, height = 214 },
				uvRect = { u0 = 0.00390625, v0 = 0.00195312, u1 = 0.472656, v1 = 0.210938 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/lodge_3x3",
				spriteColorRect = { x = 2, y = 6, width = 234, height = 216 },
				uvRect = { u0 = 0.476562, v0 = 0.00195312, u1 = 0.933594, v1 = 0.212891 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/lodge_con",
				spriteColorRect = { x = 18, y = 65, width = 222, height = 156 },
				uvRect = { u0 = 0.00390625, v0 = 0.212891, u1 = 0.4375, v1 = 0.365234 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/outhouse_a_1x1",
				spriteColorRect = { x = 7, y = 0, width = 72, height = 78 },
				uvRect = { u0 = 0.738281, v0 = 0.525391, u1 = 0.890625, v1 = 0.595703 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "obj/rock_a_1x1",
				spriteColorRect = { x = 7, y = 4, width = 72, height = 72 },
				uvRect = { u0 = 0.566406, v0 = 0.554688, u1 = 0.707031, v1 = 0.625 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/rock_b_1x1",
				spriteColorRect = { x = 2, y = 2, width = 78, height = 76 },
				uvRect = { u0 = 0.410156, v0 = 0.552734, u1 = 0.5625, v1 = 0.626953 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/stump_a_1x1",
				spriteColorRect = { x = 7, y = 9, width = 72, height = 56 },
				uvRect = { u0 = 0.296875, v0 = 0.507812, u1 = 0.40625, v1 = 0.578125 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "obj/train_clairvoyance_2x2",
				spriteColorRect = { x = 43, y = 7, width = 72, height = 150 },
				uvRect = { u0 = 0.00390625, v0 = 0.367188, u1 = 0.296875, v1 = 0.4375 },
				spriteSourceSize = { width = 160, height = 160 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "obj/train_heal_2x2",
				spriteColorRect = { x = 11, y = 2, width = 136, height = 148 },
				uvRect = { u0 = 0.00390625, v0 = 0.439453, u1 = 0.292969, v1 = 0.572266 },
				spriteSourceSize = { width = 160, height = 160 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "obj/train_levitation_2x2",
				spriteColorRect = { x = 4, y = 22, width = 156, height = 122 },
				uvRect = { u0 = 0.441406, v0 = 0.214844, u1 = 0.746094, v1 = 0.333984 },
				spriteSourceSize = { width = 160, height = 160 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/tree_a_1x1",
				spriteColorRect = { x = 3, y = 1, width = 76, height = 78 },
				uvRect = { u0 = 0.585938, v0 = 0.476562, u1 = 0.734375, v1 = 0.552734 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/tree_b_1x1",
				spriteColorRect = { x = 0, y = 2, width = 80, height = 94 },
				uvRect = { u0 = 0.75, v0 = 0.285156, u1 = 0.933594, v1 = 0.363281 },
				spriteSourceSize = { width = 80, height = 98 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "obj/tree_c_1x1",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 76 },
				uvRect = { u0 = 0.425781, v0 = 0.476562, u1 = 0.582031, v1 = 0.550781 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj/tree_d_1x1",
				spriteColorRect = { x = 6, y = 0, width = 70, height = 98 },
				uvRect = { u0 = 0.75, v0 = 0.214844, u1 = 0.941406, v1 = 0.283203 },
				spriteSourceSize = { width = 80, height = 98 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

