-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:bcd595137d3c5fad0ad6c62f08c165c8$
-- 

return {
	texture = 'sheet_bear.png',
	frames = {
			{
				name = "bear_arm_left",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 18 },
				uvRect = { u0 = 0.958984, v0 = 0.160156, u1 = 0.994141, v1 = 0.21875 },
				spriteSourceSize = { width = 60, height = 18 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "bear_arm_left1",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 17 },
				uvRect = { u0 = 0.958984, v0 = 0.220703, u1 = 0.992188, v1 = 0.279297 },
				spriteSourceSize = { width = 60, height = 17 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "bear_ruff",
				spriteColorRect = { x = 38, y = 12, width = 41, height = 19 },
				uvRect = { u0 = 0.958984, v0 = 0.118164, u1 = 0.996094, v1 = 0.158203 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_ruff_back",
				spriteColorRect = { x = 38, y = 9, width = 41, height = 21 },
				uvRect = { u0 = 0.941406, v0 = 0.28125, u1 = 0.982422, v1 = 0.321289 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing",
				spriteColorRect = { x = 6, y = 0, width = 65, height = 118 },
				uvRect = { u0 = 0.724609, v0 = 0.118164, u1 = 0.955078, v1 = 0.181641 },
				spriteSourceSize = { width = 75, height = 118 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing1",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 118 },
				uvRect = { u0 = 0.724609, v0 = 0.183594, u1 = 0.955078, v1 = 0.235352 },
				spriteSourceSize = { width = 53, height = 118 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "bear_standing_back",
				spriteColorRect = { x = 24, y = 0, width = 69, height = 115 },
				uvRect = { u0 = 0.00390625, v0 = 0.541016, u1 = 0.228516, v1 = 0.608398 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_back_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 115 },
				uvRect = { u0 = 0.484375, v0 = 0.118164, u1 = 0.720703, v1 = 0.230469 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_standing_front",
				spriteColorRect = { x = 24, y = 0, width = 69, height = 117 },
				uvRect = { u0 = 0.46875, v0 = 0.376953, u1 = 0.697266, v1 = 0.444336 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_front_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 117 },
				uvRect = { u0 = 0.724609, v0 = 0.00195312, u1 = 0.960938, v1 = 0.116211 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bear_standing_left",
				spriteColorRect = { x = 36, y = 0, width = 49, height = 117 },
				uvRect = { u0 = 0.701172, v0 = 0.485352, u1 = 0.929688, v1 = 0.533203 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_left_readytohug",
				spriteColorRect = { x = 16, y = 0, width = 75, height = 117 },
				uvRect = { u0 = 0.00390625, v0 = 0.308594, u1 = 0.232422, v1 = 0.381836 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 118 },
				uvRect = { u0 = 0.00390625, v0 = 0.00195312, u1 = 0.240234, v1 = 0.117188 },
				spriteSourceSize = { width = 121, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bear_standing_right",
				spriteColorRect = { x = 36, y = 0, width = 49, height = 117 },
				uvRect = { u0 = 0.00390625, v0 = 0.491211, u1 = 0.232422, v1 = 0.539062 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_right_readytohug",
				spriteColorRect = { x = 36, y = 0, width = 75, height = 117 },
				uvRect = { u0 = 0.236328, v0 = 0.307617, u1 = 0.464844, v1 = 0.380859 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_side",
				spriteColorRect = { x = 36, y = 0, width = 49, height = 117 },
				uvRect = { u0 = 0.236328, v0 = 0.490234, u1 = 0.464844, v1 = 0.538086 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking1",
				spriteColorRect = { x = 24, y = 0, width = 69, height = 117 },
				uvRect = { u0 = 0.701172, v0 = 0.3125, u1 = 0.929688, v1 = 0.379883 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking1_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 117 },
				uvRect = { u0 = 0.484375, v0 = 0.00195312, u1 = 0.720703, v1 = 0.116211 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bear_walking2",
				spriteColorRect = { x = 24, y = 0, width = 69, height = 117 },
				uvRect = { u0 = 0.46875, v0 = 0.307617, u1 = 0.697266, v1 = 0.375 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking2_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 117 },
				uvRect = { u0 = 0.244141, v0 = 0.00195312, u1 = 0.480469, v1 = 0.116211 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bear_walking_back1",
				spriteColorRect = { x = 24, y = 0, width = 69, height = 115 },
				uvRect = { u0 = 0.236328, v0 = 0.540039, u1 = 0.460938, v1 = 0.607422 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_back1_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 115 },
				uvRect = { u0 = 0.00390625, v0 = 0.119141, u1 = 0.240234, v1 = 0.231445 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_walking_back2",
				spriteColorRect = { x = 24, y = 0, width = 69, height = 115 },
				uvRect = { u0 = 0.46875, v0 = 0.498047, u1 = 0.693359, v1 = 0.56543 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_back2_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 115 },
				uvRect = { u0 = 0.244141, v0 = 0.118164, u1 = 0.480469, v1 = 0.230469 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_walking_left1",
				spriteColorRect = { x = 35, y = 0, width = 53, height = 117 },
				uvRect = { u0 = 0.00390625, v0 = 0.4375, u1 = 0.232422, v1 = 0.489258 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_left1_readytohug",
				spriteColorRect = { x = 16, y = 0, width = 75, height = 117 },
				uvRect = { u0 = 0.708984, v0 = 0.237305, u1 = 0.9375, v1 = 0.310547 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_left2",
				spriteColorRect = { x = 35, y = 0, width = 53, height = 117 },
				uvRect = { u0 = 0.236328, v0 = 0.436523, u1 = 0.464844, v1 = 0.488281 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_left2_readytohug",
				spriteColorRect = { x = 16, y = 0, width = 75, height = 117 },
				uvRect = { u0 = 0.476562, v0 = 0.232422, u1 = 0.705078, v1 = 0.305664 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_right1",
				spriteColorRect = { x = 36, y = 0, width = 51, height = 117 },
				uvRect = { u0 = 0.46875, v0 = 0.446289, u1 = 0.697266, v1 = 0.496094 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_right1_readytohug",
				spriteColorRect = { x = 38, y = 0, width = 75, height = 117 },
				uvRect = { u0 = 0.00390625, v0 = 0.233398, u1 = 0.232422, v1 = 0.306641 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_right2",
				spriteColorRect = { x = 35, y = 0, width = 53, height = 117 },
				uvRect = { u0 = 0.00390625, v0 = 0.383789, u1 = 0.232422, v1 = 0.435547 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_right2_readytohug",
				spriteColorRect = { x = 32, y = 0, width = 75, height = 117 },
				uvRect = { u0 = 0.244141, v0 = 0.232422, u1 = 0.472656, v1 = 0.305664 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side",
				spriteColorRect = { x = 36, y = 0, width = 51, height = 117 },
				uvRect = { u0 = 0.701172, v0 = 0.433594, u1 = 0.929688, v1 = 0.483398 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side1",
				spriteColorRect = { x = 36, y = 0, width = 51, height = 117 },
				uvRect = { u0 = 0.701172, v0 = 0.381836, u1 = 0.929688, v1 = 0.431641 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side2",
				spriteColorRect = { x = 35, y = 0, width = 53, height = 117 },
				uvRect = { u0 = 0.236328, v0 = 0.382812, u1 = 0.464844, v1 = 0.43457 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

