-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:502b5ab4509eb6a6e1516f6be721ac5f$
-- 

return {
	texture = 'sheet_bearface.png',
	frames = {
			{
				name = "happier bear face",
				spriteColorRect = { x = 0, y = 0, width = 800, height = 600 },
				uvRect = { u0 = 0.294922, v0 = 0.294922, u1 = 0.587891, v1 = 0.685547 },
				spriteSourceSize = { width = 800, height = 600 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "happy bear face",
				spriteColorRect = { x = 0, y = 0, width = 800, height = 600 },
				uvRect = { u0 = 0.000976562, v0 = 0.686523, u1 = 0.391602, v1 = 0.979492 },
				spriteSourceSize = { width = 800, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "normal bear face",
				spriteColorRect = { x = 0, y = 0, width = 800, height = 600 },
				uvRect = { u0 = 0.000976562, v0 = 0.294922, u1 = 0.293945, v1 = 0.685547 },
				spriteSourceSize = { width = 800, height = 600 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "sad bear face",
				spriteColorRect = { x = 0, y = 0, width = 800, height = 600 },
				uvRect = { u0 = 0.392578, v0 = 0.000976562, u1 = 0.783203, v1 = 0.293945 },
				spriteSourceSize = { width = 800, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sadder bear face",
				spriteColorRect = { x = 0, y = 0, width = 800, height = 600 },
				uvRect = { u0 = 0.000976562, v0 = 0.000976562, u1 = 0.391602, v1 = 0.293945 },
				spriteSourceSize = { width = 800, height = 600 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

