-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:984ef23fe1c637bb69aebfd7e801d2d7$
-- 

return {
	texture = 'sheet_bear.png',
	frames = {
			{
				name = "bear_standing",
				spriteColorRect = { x = 6, y = 0, width = 65, height = 118 },
				uvRect = { u0 = 0.488281, v0 = 0.232422, u1 = 0.949219, v1 = 0.359375 },
				spriteSourceSize = { width = 75, height = 118 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing1",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 118 },
				uvRect = { u0 = 0.0078125, v0 = 0.238281, u1 = 0.46875, v1 = 0.341797 },
				spriteSourceSize = { width = 53, height = 118 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "bear_standing_back",
				spriteColorRect = { x = 35, y = 0, width = 47, height = 115 },
				uvRect = { u0 = 0.0078125, v0 = 0.775391, u1 = 0.457031, v1 = 0.867188 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_back_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 115 },
				uvRect = { u0 = 0.488281, v0 = 0.00390625, u1 = 0.960938, v1 = 0.228516 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_standing_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 118 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.480469, v1 = 0.234375 },
				spriteSourceSize = { width = 121, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bear_standing_side",
				spriteColorRect = { x = 36, y = 0, width = 49, height = 117 },
				uvRect = { u0 = 0.472656, v0 = 0.589844, u1 = 0.929688, v1 = 0.685547 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking1",
				spriteColorRect = { x = 25, y = 0, width = 61, height = 117 },
				uvRect = { u0 = 0.472656, v0 = 0.363281, u1 = 0.929688, v1 = 0.482422 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking2",
				spriteColorRect = { x = 31, y = 0, width = 61, height = 117 },
				uvRect = { u0 = 0.0078125, v0 = 0.345703, u1 = 0.464844, v1 = 0.464844 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_back1",
				spriteColorRect = { x = 35, y = 0, width = 47, height = 115 },
				uvRect = { u0 = 0.464844, v0 = 0.689453, u1 = 0.914062, v1 = 0.78125 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_back2",
				spriteColorRect = { x = 35, y = 0, width = 47, height = 115 },
				uvRect = { u0 = 0.0078125, v0 = 0.679688, u1 = 0.457031, v1 = 0.771484 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side",
				spriteColorRect = { x = 36, y = 0, width = 51, height = 117 },
				uvRect = { u0 = 0.0078125, v0 = 0.576172, u1 = 0.464844, v1 = 0.675781 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side1",
				spriteColorRect = { x = 36, y = 0, width = 51, height = 117 },
				uvRect = { u0 = 0.472656, v0 = 0.486328, u1 = 0.929688, v1 = 0.585938 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side2",
				spriteColorRect = { x = 35, y = 0, width = 53, height = 117 },
				uvRect = { u0 = 0.0078125, v0 = 0.46875, u1 = 0.464844, v1 = 0.572266 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

