-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:34deddd8f97d40e096821b1f7a3cb8e7$
-- 

return {
	texture = 'sheet_bear.png',
	frames = {
			{
				name = "bear_standing",
				spriteColorRect = { x = 6, y = 0, width = 65, height = 118 },
				uvRect = { u0 = 0.0078125, v0 = 0.238281, u1 = 0.46875, v1 = 0.365234 },
				spriteSourceSize = { width = 75, height = 118 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing1",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 118 },
				uvRect = { u0 = 0.0078125, v0 = 0.369141, u1 = 0.46875, v1 = 0.472656 },
				spriteSourceSize = { width = 53, height = 118 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "bear_standing_back",
				spriteColorRect = { x = 35, y = 0, width = 47, height = 115 },
				uvRect = { u0 = 0.0078125, v0 = 0.898438, u1 = 0.457031, v1 = 0.990234 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_standing_back_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 115 },
				uvRect = { u0 = 0.488281, v0 = 0.236328, u1 = 0.960938, v1 = 0.460938 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bear_standing_front_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 117 },
				uvRect = { u0 = 0.488281, v0 = 0.00390625, u1 = 0.960938, v1 = 0.232422 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bear_standing_readytohug",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 118 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.480469, v1 = 0.234375 },
				spriteSourceSize = { width = 121, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bear_standing_side",
				spriteColorRect = { x = 36, y = 0, width = 49, height = 117 },
				uvRect = { u0 = 0.0078125, v0 = 0.703125, u1 = 0.464844, v1 = 0.798828 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking1",
				spriteColorRect = { x = 25, y = 0, width = 61, height = 117 },
				uvRect = { u0 = 0.0078125, v0 = 0.476562, u1 = 0.464844, v1 = 0.595703 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking2",
				spriteColorRect = { x = 31, y = 0, width = 61, height = 117 },
				uvRect = { u0 = 0.476562, v0 = 0.464844, u1 = 0.933594, v1 = 0.583984 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_back1",
				spriteColorRect = { x = 35, y = 0, width = 47, height = 115 },
				uvRect = { u0 = 0.0078125, v0 = 0.802734, u1 = 0.457031, v1 = 0.894531 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_back2",
				spriteColorRect = { x = 35, y = 0, width = 47, height = 115 },
				uvRect = { u0 = 0.472656, v0 = 0.798828, u1 = 0.921875, v1 = 0.890625 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side",
				spriteColorRect = { x = 36, y = 0, width = 51, height = 117 },
				uvRect = { u0 = 0.472656, v0 = 0.695312, u1 = 0.929688, v1 = 0.794922 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side1",
				spriteColorRect = { x = 36, y = 0, width = 51, height = 117 },
				uvRect = { u0 = 0.0078125, v0 = 0.599609, u1 = 0.464844, v1 = 0.699219 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bear_walking_side2",
				spriteColorRect = { x = 35, y = 0, width = 53, height = 117 },
				uvRect = { u0 = 0.472656, v0 = 0.587891, u1 = 0.929688, v1 = 0.691406 },
				spriteSourceSize = { width = 121, height = 117 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

